#!/bin/sh

alias ls="ls -hN --color=auto --group-directories-first"
alias lsa="ls -a"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# FLTR (Russian)
alias fltr='nohup java -jar /home/kyle/Documents/Russian/FLTR.jar &'

# some more ls aliases
alias config='/usr/bin/git --git-dir=/home/kyle/.cfg/ --work-tree=/home/kyle'

#dotfiles
# https://www.atlassian.com/git/tutorials/dotfiles
alias dotfiles='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias dotfilesstatus='dotfiles status'
alias dotfilesadd='dotfiles add'
alias dotfilescommit='dotfiles commit -m'
alias dotfilespush='dotfiles push'


