#!/bin/sh

alias ls="ls -hN --color=auto --group-directories-first"
alias lsa="ls -a"

# FLTR (Russian)
alias fltr='nohup java -jar /home/kyle/Documents/Russian/FLTR.jar &'


#dotfiles
# https://www.atlassian.com/git/tutorials/dotfiles
alias dotfiles='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias dotfilesstatus='dotfiles status'
alias dotfilesadd='dotfiles add'
alias dotfilescommit='dotfiles commit -m'
alias dotfilespush='dotfiles push'


